import { notFound } from "next/navigation"; import { prisma } from "@/lib/prisma"; import { Card } from "@/components/ui/Card"; import { BarChart3 } from "lucide-react";

export default async function StandingsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const tournament = await prisma.tournament.findUnique({ where: { id }, include: { pools: { include: { standings: { include: { team: true }, orderBy: { rank: "asc" } } }, orderBy: { sortOrder: "asc" } } } }); if (!tournament) notFound();
  if (tournament.pools.length === 0) return (<div className="text-center py-16"><BarChart3 size={48} className="mx-auto text-[var(--text-muted)] mb-4" strokeWidth={1} /><p className="font-display text-[28px] tracking-wider text-[var(--text-secondary)]">NO STANDINGS</p><p className="text-[14px] text-[var(--text-muted)] mt-2">Standings appear after matches begin</p></div>);
  const settings = JSON.parse(tournament.settings || "{}");
  return (
    <div><h1 className="font-display text-[clamp(36px,5vw,52px)] tracking-wider text-[var(--text-primary)] leading-none mb-8">STANDINGS</h1><div className="space-y-6">
      {tournament.pools.map((pool: typeof tournament.pools[number]) => (<Card key={pool.id} padding={false}>
        <div className="p-4 sm:p-5 border-b border-[var(--border)]"><h2 className="font-display text-[24px] tracking-wider text-[var(--text-primary)]">{pool.name.toUpperCase()}</h2></div>
        <div className="sm:hidden divide-y divide-[var(--border)]">{pool.standings.map((s: typeof pool.standings[number], i: number) => (<div key={s.id} className="p-3 flex items-center gap-3"><span className="font-display text-[24px] tracking-wider text-[var(--text-muted)] w-8 text-center">{s.rank ?? i + 1}</span><div className="flex-1 min-w-0"><p className="text-[15px] font-semibold text-[var(--text-primary)] truncate">{s.team.name}</p><p className="text-[12px] text-[var(--text-muted)]">{s.wins}W-{s.losses}L &middot; {s.setsWon}-{s.setsLost} sets</p></div>{settings.advancePerPool && (s.rank ?? i + 1) <= settings.advancePerPool && <span className="text-[11px] font-bold text-[var(--success)] uppercase tracking-widest">Q</span>}</div>))}</div>
        <div className="hidden sm:block overflow-x-auto"><table className="w-full text-[14px]"><thead><tr className="border-b border-[var(--border)]">{["#", "Team", "MP", "W", "L", "Sets", "Pts"].map((h, i) => (<th key={h} className={`px-4 py-3 text-[10px] font-bold text-[var(--text-muted)] uppercase tracking-[0.2em] ${i < 2 ? "text-left" : "text-center"} ${i === 0 ? "w-12" : ""}`}>{h}</th>))}</tr></thead><tbody>{pool.standings.map((s: typeof pool.standings[number], i: number) => (<tr key={s.id} className={`border-b border-[var(--border)] ${settings.advancePerPool && (s.rank ?? i + 1) <= settings.advancePerPool ? "bg-[var(--success-soft)]" : ""}`}><td className="px-4 py-3 font-display text-[18px] tracking-wider text-[var(--text-muted)]">{s.rank ?? i + 1}</td><td className="px-4 py-3 font-semibold text-[var(--text-primary)]">{s.team.name}</td><td className="px-4 py-3 text-center text-[var(--text-muted)]">{s.matchesPlayed}</td><td className="px-4 py-3 text-center text-[var(--text-primary)] font-semibold">{s.wins}</td><td className="px-4 py-3 text-center text-[var(--text-muted)]">{s.losses}</td><td className="px-4 py-3 text-center text-[var(--text-muted)]">{s.setsWon}-{s.setsLost}</td><td className="px-4 py-3 text-center text-[var(--text-muted)]">{s.pointsFor}-{s.pointsAgainst}</td></tr>))}</tbody></table></div>
      </Card>))}
    </div></div>
  );
}
